version: '3.8'

services:
  web:
    build: .
    restart: always
    env_file:
      - .env
    volumes:
      - static_volume:/app/staticfiles
      - media_volume:/app/mediafiles
    depends_on:
      - redis

  nginx:
    image: nginx:alpine
    restart: always
    volumes:
      - static_volume:/app/staticfiles
      - media_volume:/app/mediafiles
      - ./nginx:/etc/nginx/conf.d
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - web

  redis:
    image: redis:alpine
    restart: always

volumes:
  static_volume:
  media_volume: 