version: '3.8'

services:
  web:
    build: .
    restart: always
    env_file:
      - .env
    volumes:
      - static_volume:/app/staticfiles
    expose:
      - 8000

  nginx:
    image: nginx:alpine
    restart: always
    volumes:
      - static_volume:/app/staticfiles
      - ./nginx:/etc/nginx/conf.d
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - web

volumes:
  static_volume: 