version: '3.8'

services:
  web:
    build: .
    restart: always
    env_file:
      - .env
    volumes:
      - .:/app
      - static_volume:/app/staticfiles
    expose:
      - 8000
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health/"]
      interval: 30s
      timeout: 10s
      retries: 3

  nginx:
    image: nginx:alpine
    restart: always
    volumes:
      - static_volume:/app/staticfiles
      - ./nginx:/etc/nginx/conf.d
      - /etc/nginx/ssl:/etc/nginx/ssl:ro
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - web

volumes:
  static_volume: 