version: '3.8'

services:
  web:
    build: .
    command: gunicorn tiktok_commenter.wsgi:application --bind 0.0.0.0:8000
    volumes:
      - ./staticfiles:/app/staticfiles
      - ./media:/app/media
    expose:
      - 8000
    environment:
      - DJANGO_SETTINGS_MODULE=tiktok_commenter.settings
      - DATABASE_URL=postgres://postgres.bhryplxtproznrmtvvri:Zc1269zc!zc1269zc@aws-0-us-east-2.pooler.supabase.com:6543/postgres
      - DJANGO_SECRET_KEY=${DJANGO_SECRET_KEY}
      - DJANGO_DEBUG=0
      - DOMAIN=solforge.live
    restart: unless-stopped
    depends_on:
      - redis

  nginx:
    build: ./nginx
    volumes:
      - ./staticfiles:/app/staticfiles
      - ./media:/app/media
      - ./nginx/conf.d:/etc/nginx/conf.d
      - ./certbot/conf:/etc/letsencrypt
      - ./certbot/www:/var/www/certbot
    ports:
      - "80:80"
      - "443:443"
    restart: unless-stopped
    depends_on:
      - web

  redis:
    image: redis:alpine
    command: redis-server --appendonly yes
    volumes:
      - redis_data:/data
    expose:
      - 6379
    restart: unless-stopped

  certbot:
    image: certbot/certbot
    volumes:
      - ./certbot/conf:/etc/letsencrypt
      - ./certbot/www:/var/www/certbot
    command: certonly --webroot -w /var/www/certbot --force-renewal --email your-email@example.com -d solforge.live -d www.solforge.live --agree-tos --no-eff-email
    depends_on:
      - nginx

volumes:
  redis_data:

networks:
  default:
    driver: bridge 